# Generated by Django 5.2.7 on 2025-10-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_itemnamemodel_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sionnormclassmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sionnormclassmodel',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='sionnormclassmodel',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='sionnormclassmodel',
            name='modified_on',
        ),
    ]
