# Generated by Django 4.2.21 on 2025-07-21 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_itemnamemodel_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headsionnormsmodel',
            name='is_fetch',
        ),
        migrations.RemoveField(
            model_name='headsionnormsmodel',
            name='tcurrent',
        ),
        migrations.RemoveField(
            model_name='headsionnormsmodel',
            name='tpages',
        ),
        migrations.RemoveField(
            model_name='headsionnormsmodel',
            name='url',
        ),
        migrations.RemoveField(
            model_name='sionexportmodel',
            name='hs_code',
        ),
        migrations.RemoveField(
            model_name='sionexportmodel',
            name='item',
        ),
        migrations.RemoveField(
            model_name='sionimportmodel',
            name='hs_code',
        ),
        migrations.RemoveField(
            model_name='sionimportmodel',
            name='item',
        ),
        migrations.RemoveField(
            model_name='sionnormclassmodel',
            name='is_fetch',
        ),
        migrations.RemoveField(
            model_name='sionnormclassmodel',
            name='item',
        ),
        migrations.RemoveField(
            model_name='sionnormclassmodel',
            name='url',
        ),
        migrations.AddField(
            model_name='sionexportmodel',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sionimportmodel',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sionnormclassmodel',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sionexportmodel',
            name='norm_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_norm', to='core.sionnormclassmodel'),
        ),
    ]
