# Generated by Django 4.2.21 on 2025-08-01 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_companymodel_created_by_companymodel_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address_line_1', models.TextField()),
                ('address_line_2', models.TextField(blank=True)),
                ('pan_number', models.CharField(max_length=10)),
                ('gst_number', models.CharField(max_length=15)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('current', 'Current'), ('saving', 'Saving')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='companymodel',
            name='director_1',
        ),
        migrations.RemoveField(
            model_name='companymodel',
            name='director_2',
        ),
        migrations.RemoveField(
            model_name='companymodel',
            name='failed',
        ),
        migrations.RemoveField(
            model_name='companymodel',
            name='is_fetch',
        ),
        migrations.RemoveField(
            model_name='companymodel',
            name='is_ge',
        ),
        migrations.AddField(
            model_name='companymodel',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number.', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')]),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='pan',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')]),
        ),
    ]
