# Generated by Django 4.2.21 on 2025-08-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_invoiceentity_remove_companymodel_director_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceentity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='entity_logos/'),
        ),
    ]
