# Generated by Django 4.2.21 on 2025-08-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_invoiceentity_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceentity',
            name='bill_colour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceentity',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='entity_signature/'),
        ),
    ]
