# Generated by Django 4.2.21 on 2025-08-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_invoiceentity_bill_colour_invoiceentity_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceentity',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to='entity_stamp/'),
        ),
    ]
