# Generated by Django 4.2.21 on 2025-08-06 08:42

from django.db import migrations


def create_initial_entity(apps, schema_editor):
    InvoiceEntity = apps.get_model('core', 'InvoiceEntity')
    InvoiceEntity.objects.create(
        name='LABDHI MERCANTILE LLP',
        address_line_1='1109, 11th Floor, Ncp Supremus Wing, New Cuff Parade',
        address_line_2='Antop Hill, Mumbai, Mumbai, Maharashtra, India, 400037',
        pan_number='CMTPS5662M',
        gst_number='27CMTPS5662M1ZW',
        logo='entity_logos/logo.png',
        signature='entity_signature/signature.png',
        stamp='entity_stamp/stamp.png',
        bank_account_number='400000070225',
        bank_name='RBL BANK',
        ifsc_code='RATN0000286',
        account_type='current',
    )


def delete_initial_entity(apps, schema_editor):
    InvoiceEntity = apps.get_model('core', 'InvoiceEntity')
    InvoiceEntity.objects.filter(name='LABDHI MERCANTILE LLP').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_invoiceentity_stamp'),
    ]

    operations = [
        migrations.RunPython(create_initial_entity, reverse_code=delete_initial_entity),
    ]
