# Generated by Django 4.2.21 on 2025-09-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_notificationnumber_purchasestatus_schemecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sionimportmodel',
            name='hsn_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sion_imports', to='core.hscodemodel'),
        ),
    ]
