# Generated by Django 4.2.21 on 2025-08-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_notificationnumber_purchasestatus_schemecode'),
    ]

    operations = [
    ]
