# Generated by Django 4.2.21 on 2025-09-22 08:36

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_sionimportmodel_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('OD', 'Overdraft')], max_length=20, null=True, verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='bill_colour',
            field=models.CharField(default='#333', max_length=20),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code.', regex='^[A-Z]{4}0[A-Z0-9]{6}$')], verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.company_upload_path),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.company_upload_path),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.company_upload_path),
        ),
    ]
