# Generated by Django 3.1.6 on 2022-05-25 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('allotment', '0001_initial'),
        ('core', '0001_initial'),
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_of_entry_number', models.CharField(max_length=25, unique=True)),
                ('bill_of_entry_date', models.DateField(blank=True, null=True)),
                ('exchange_rate', models.FloatField(default=0)),
                ('product_name', models.CharField(default='', max_length=255)),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('is_fetch', models.BooleanField(default=False)),
                ('failed', models.IntegerField(default=0)),
                ('appraisement', models.CharField(blank=True, max_length=255, null=True)),
                ('ooc_date', models.CharField(blank=True, max_length=255, null=True)),
                ('cha', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('allotment',
                 models.ManyToManyField(blank=True, related_name='bill_of_entry', to='allotment.AllotmentModel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='bill_of_entry', to='core.companymodel')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='boe_port', to='core.portmodel')),
            ],
            options={
                'ordering': ('-bill_of_entry_date',),
            },
        ),
        migrations.CreateModel(
            name='RowDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type',
                 models.CharField(choices=[('AR', 'ARO'), ('AT', 'Allotment')], default='AT', max_length=2)),
                ('transaction_type',
                 models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default='D', max_length=2)),
                ('cif_inr', models.FloatField(default=0.0)),
                ('cif_fc', models.FloatField(default=0.0)),
                ('qty', models.FloatField(default=0.0)),
                ('bill_of_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='item_details', to='bill_of_entry.billofentrymodel')),
                ('sr_number',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_details',
                                   to='license.licenseimportitemsmodel')),
            ],
            options={
                'ordering': ['transaction_type', 'bill_of_entry__bill_of_entry_date'],
            },
        ),
    ]
