# Generated by Django 4.2.21 on 2025-07-25 15:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill_of_entry', '0004_alter_rowdetails_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofentrymodel',
            options={'ordering': ('-bill_of_entry_date',), 'verbose_name': 'Bill of Entry', 'verbose_name_plural': 'Bills of Entry'},
        ),
        migrations.AlterModelOptions(
            name='rowdetails',
            options={'ordering': ['transaction_type', 'bill_of_entry__bill_of_entry_date'], 'verbose_name': 'Item Detail', 'verbose_name_plural': 'Item Details'},
        ),
        migrations.AddField(
            model_name='billofentrymodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billofentrymodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofentrymodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billofentrymodel',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rowdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rowdetails',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rowdetails',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rowdetails',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billofentrymodel',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='rowdetails',
            name='cif_fc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='rowdetails',
            name='cif_inr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='rowdetails',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
    ]
