# Generated by Django 4.2.21 on 2025-08-01 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_invoiceentity_remove_companymodel_director_1_and_more'),
        ('bill_of_entry', '0005_alter_billofentrymodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('to_company_name', models.CharField(max_length=255)),
                ('to_company_address', models.TextField()),
                ('to_company_pan', models.CharField(blank=True, max_length=20, null=True)),
                ('to_company_gst', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_mode', models.CharField(choices=[('kg', 'KG'), ('cif', 'CIF INR')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_in_words', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.invoiceentity')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(max_length=20)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cif_fc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cif_inr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bill_of_entry.invoice')),
            ],
        ),
    ]
