# Generated by Django 4.2.21 on 2025-08-01 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0032_alter_licensedetailsmodel_purchase_status'),
        ('core', '0018_invoiceentity_remove_companymodel_director_1_and_more'),
        ('bill_of_entry', '0006_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='invoice_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='amount_in_words',
            new_name='to_company_address_line_1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='to_company_address',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='to_company_address_line_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_cif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sr_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='license.licenseimportitemsmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_mode',
            field=models.CharField(choices=[('kg', 'KG'), ('cif', 'CIF')], max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='from_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoiceentity'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='to_company_gst',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='to_company_pan',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='cif_fc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='cif_inr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='hsn_code',
            field=models.CharField(default='490700', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='license_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
