# Generated by Django 4.2.21 on 2025-08-03 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0008_invoice_bills_of_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='to_company_gst',
        ),
        migrations.AddField(
            model_name='invoice',
            name='to_company_gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number.', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='to_company_pan',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')]),
        ),
    ]
