# Generated by Django 4.2.21 on 2025-08-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0009_remove_invoice_to_company_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_amount_in_words',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
