# Generated by Django 4.2.21 on 2025-08-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0010_invoice_total_amount_in_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total_cif',
            new_name='total_cif_fc',
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_cif_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
