# Generated by Django 4.2.21 on 2025-08-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0011_rename_total_cif_invoice_total_cif_fc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount_in_words',
            field=models.TextField(blank=True, null=True),
        ),
    ]
