# Generated by Django 4.2.21 on 2025-09-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0012_alter_invoice_total_amount_in_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='sr_number',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
