# Generated by Django 4.2.21 on 2025-09-07 18:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseTradePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trade.licensetrade')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='TradePayment',
        ),
    ]
