# Generated by Django 4.2.21 on 2025-09-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_licensetradepayment_delete_tradepayment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='licensetrade',
            constraint=models.CheckConstraint(check=models.Q(('from_company__isnull', True), ('to_company__isnull', True), models.Q(('from_company', models.F('to_company')), _negated=True), _connector='OR'), name='chk_from_to_companies_different'),
        ),
        migrations.AddConstraint(
            model_name='licensetrade',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'PURCHASE')), fields=('from_company', 'invoice_number'), name='uniq_purchase_supplier_invoice'),
        ),
        migrations.AddConstraint(
            model_name='licensetrade',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'SALE')), fields=('to_company', 'invoice_number'), name='uniq_sale_buyer_invoice'),
        ),
    ]
