# Generated by Django 4.2.21 on 2025-09-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_licensetrade_chk_from_to_companies_different_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='licensetrade',
            name='uniq_purchase_supplier_invoice',
        ),
        migrations.RemoveConstraint(
            model_name='licensetrade',
            name='uniq_sale_buyer_invoice',
        ),
        migrations.AddConstraint(
            model_name='licensetrade',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'PURCHASE'), models.Q(('invoice_number', ''), _negated=True)), fields=('from_company', 'invoice_number'), name='uniq_purchase_supplier_invoice'),
        ),
        migrations.AddConstraint(
            model_name='licensetrade',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'SALE'), models.Q(('invoice_number', ''), _negated=True)), fields=('to_company', 'invoice_number'), name='uniq_sale_buyer_invoice_nonblank'),
        ),
    ]
