# Generated by Django 4.2.21 on 2025-09-16 01:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_remove_licensetrade_uniq_purchase_supplier_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetradeline',
            name='cif_fc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='licensetradeline',
            name='exc_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
    ]
