from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

urlpatterns = [
    path('licence/report/biscuits/', login_required(views.PDFSummaryLicenseDetailView.as_view()),
         name='licence_report_biscuits_new'),
    path('analysis/', login_required(views.analysis), name='analysis'),
    path('add/', login_required(views.LicenseDetailCreateView.as_view()), name='license-add'),
    path('<slug:license>/new/', login_required(views.DFIADetailView.as_view()), name='dfia-details'),
    path('<slug:license>/card/', login_required(views.LicenseCardView.as_view()), name='license-card'),
    path('', login_required(views.LicenseListView.as_view()), name='license-list'),
    path('ajax/', login_required(views.LicenseAjaxListView.as_view()), name='license-ajax-list'),
    path('<slug:license>/update', login_required(views.LicenseDetailUpdateView.as_view()), name='license-update'),
    path('<slug:license>/', login_required(views.LicenseDetailView.as_view()), name='license-detail'),
    path('<slug:license>/item/update', login_required(views.LicenseItemListUpdateView.as_view()),
         name='license-item-update'),
    path('<int:pk>/verify', login_required(views.LicenseVerifyView.as_view()), name='license-verify'),
    path('<slug:license>.pdf', login_required(views.PDFLicenseDetailView.as_view()), name='license-pdf'),
    path('amd/<slug:license>.pdf', login_required(views.PDFAmendmentLicenseDetailView.as_view()),
         name='amend-license-pdf'),
    path('<slug:license>.xlsx', login_required(views.ExcelLicenseDetailView.as_view()), name='license-excel'),
    path('ledger/<slug:license>.pdf', login_required(views.PDFLedgerLicenseDetailView.as_view()),
         name='license_ledger'),
    path('ledger/item/<slug:license>.pdf', login_required(views.PDFLedgerItemLicenseDetailView.as_view()),
         name='license_item_ledger_pdf'),
    path('item/report', login_required(views.ItemReportView.as_view()),
         name='item_report'),
    path('item/report/list/', login_required(views.ItemListReportView.as_view()),
         name='item_report_list'),
    path('calc/premium', login_required(views.PremiumCalculationView.as_view()), name='premium'),
    path('generate/report', login_required(views.LicenseReportListView.as_view()), name='report_list'),
    path('consolidate/pdf', login_required(views.LicensePDFConsolidateView.as_view()), name='consolidate'),
    path('movement/list/', login_required(views.MovementListView.as_view()), name='movement-list'),
    path('movement/update/', login_required(views.MovementUpdateView.as_view()), name='movement-update'),
    path('summary/<slug:license>.pdf', login_required(views.PDFSummaryLicenseDetailView.as_view()),
         name='license_summary'),
    path('report/biscuit/<slug:status>/<slug:party>/', login_required(views.BiscuitReportView.as_view()), name='report_biscuit'),
    path('report/confectionery/<slug:status>', login_required(views.ConfectioneryReportView.as_view()),
         name='report_confectionery'),
    path('report/namkeen/<slug:status>', login_required(views.NamkeenReportView.as_view()),
         name='report_namkeen'),
    path('report/tractor/<slug:status>', login_required(views.TractorReportView.as_view()),
         name='report_tractor'),
    path('report/steel/<slug:status>', login_required(views.SteelReportView.as_view()),
         name='report_steel'),
    path('report/glass/<slug:status>', login_required(views.GlassReportView.as_view()),
         name='report_glass'),
    path('report/pickle/<slug:status>', login_required(views.PickleReportView.as_view()),
         name='report_pickle'),
]
