# Generated by Django 3.1.6 on 2022-05-25 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllotmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_created=True, blank=True, null=True)),
                ('type', models.CharField(choices=[('AR', 'ARO'), ('AT', 'Allotment')], default='AT', max_length=2)),
                ('required_quantity', models.FloatField(default=0)),
                ('unit_value_per_unit', models.FloatField(default=0)),
                ('item_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_arrival_date', models.DateField(blank=True, null=True)),
                ('bl_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_on', models.DateField(auto_now=True)),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_allotments',
                                   to='core.companymodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='allotment_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='allotment_updated', to=settings.AUTH_USER_MODEL)),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to='core.portmodel')),
                ('related_company',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='related_company', to='core.companymodel')),
            ],
            options={
                'ordering': ['estimated_arrival_date'],
            },
        ),
        migrations.CreateModel(
            name='AllotmentItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif_inr', models.FloatField(default=0.0)),
                ('cif_fc', models.FloatField(default=0.0)),
                ('qty', models.FloatField(default=0.0)),
                ('is_boe', models.BooleanField(default=False)),
                ('allotment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='allotment_details', to='allotment.allotmentmodel')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='allotment_details', to='license.licenseimportitemsmodel')),
            ],
            options={
                'ordering': ['qty'],
            },
        ),
    ]
