# Generated by Django 5.2.7 on 2025-10-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0003_alter_allotmentitems_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allotmentmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='allotmentmodel',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='allotmentmodel',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='allotmentmodel',
            name='modified_on',
        ),
    ]
