# Generated by Django 4.2.21 on 2025-08-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0004_allotmentitems_created_by_allotmentitems_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotmentmodel',
            name='exchange_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allotmentmodel',
            name='required_cif_fc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allotmentmodel',
            name='required_cif_inr',
            field=models.FloatField(default=0),
        ),
    ]
