# Generated by Django 4.2.21 on 2025-08-10 10:48

from django.db import migrations
from django.db.models import F, Value, FloatField
from django.db.models.functions import Coalesce


def forwards(apps, schema_editor):
    Allotment = apps.get_model("allotment", "AllotmentModel")
    # required_cif_fc = COALESCE(required_quantity, 0) * COALESCE(unit_value_per_unit, 0)
    Allotment.objects.update(
        required_cif_fc=Coalesce(F("required_quantity"), Value(0.0), output_field=FloatField())
                        * Coalesce(F("unit_value_per_unit"), Value(0.0), output_field=FloatField())
    )


class Migration(migrations.Migration):
    dependencies = [
        ('allotment', '0005_allotmentmodel_exchange_rate_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
