# Generated by Django 4.2.14 on 2024-08-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0013_remove_licensedetailsmodel_is_ge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='license_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
