# Generated by Django 4.2.21 on 2025-08-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20250806_0842'),
        ('license', '0032_alter_licensedetailsmodel_purchase_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='licenseimportitemsmodel',
            name='license_lic_item_id_c3fee2_idx',
        ),
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='item',
        ),
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='license_import_item', to='core.itemnamemodel'),
        ),
    ]
