# Generated by Django 5.2.7 on 2025-10-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0032_alter_licensedetailsmodel_purchase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='modified_on',
        ),
    ]
