# Generated by Django 4.2.21 on 2025-09-01 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_notificationnumber_purchasestatus_schemecode'),
        ('license', '0035_alter_alongwithmodel_id_alter_datemodel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('supplier_pan', models.CharField(blank=True, max_length=32, null=True)),
                ('supplier_gst', models.CharField(blank=True, max_length=32, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=128, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_copy', models.FileField(blank=True, null=True, upload_to='license_purchases/invoices/')),
                ('mode', models.CharField(choices=[('AMOUNT', 'Amount-based'), ('QTY', 'Quantity-based')], default='AMOUNT', max_length=10)),
                ('amount_source', models.CharField(choices=[('FOB_INR', 'FOB (INR)'), ('CIF_INR', 'CIF (INR)'), ('CIF_USD', 'CIF (USD)')], default='FOB_INR', max_length=10)),
                ('fob_inr', models.FloatField(default=0)),
                ('cif_inr', models.FloatField(default=0)),
                ('cif_usd', models.FloatField(default=0)),
                ('exchange_rate', models.FloatField(default=0)),
                ('markup_pct', models.FloatField(default=0)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_kg', models.FloatField(default=0)),
                ('rate_inr', models.FloatField(default=0)),
                ('amount_inr', models.FloatField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='license.licensedetailsmodel')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('purchasing_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_purchases', to='core.companymodel')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_purchases', to='core.companymodel')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
