# Generated by Django 4.2.21 on 2025-09-02 12:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_notificationnumber_purchasestatus_schemecode'),
        ('bill_of_entry', '0013_remove_invoiceitem_invoice_and_more'),
        ('license', '0036_licensepurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_company_name', models.CharField(max_length=255)),
                ('to_company_pan', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('to_company_gst_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number.', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('to_company_address_line_1', models.TextField()),
                ('to_company_address_line_2', models.TextField(blank=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('billing_mode', models.CharField(choices=[('kg', 'KG'), ('cif', 'CIF')], max_length=10)),
                ('total_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_cif_fc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cif_inr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount_in_words', models.TextField(blank=True, null=True)),
                ('bills_of_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='bill_of_entry.billofentrymodel')),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoiceentity')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=50)),
                ('hsn_code', models.CharField(default='490700', max_length=10)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('cif_fc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cif_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='license.invoice')),
                ('sr_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='license.licenseimportitemsmodel')),
            ],
        ),
    ]
