# Generated by Django 4.2.21 on 2025-09-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0037_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sale_type',
            field=models.CharField(choices=[('item', 'Item'), ('full', 'Full')], default='item', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_fob_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='fob_inr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_mode',
            field=models.CharField(choices=[('kg', 'KG'), ('cif', 'CIF %'), ('fob', 'FOB %')], max_length=10),
        ),
    ]
