# Generated by Django 4.2.21 on 2025-09-07 11:54

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_sionimportmodel_hsn_code'),
        ('bill_of_entry', '0013_remove_invoiceitem_invoice_and_more'),
        ('license', '0039_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale')], db_index=True, max_length=10)),
                ('from_pan', models.CharField(blank=True, max_length=32, null=True)),
                ('from_gst', models.CharField(blank=True, max_length=32, null=True)),
                ('from_addr_line_1', models.TextField(blank=True, null=True)),
                ('from_addr_line_2', models.TextField(blank=True, null=True)),
                ('to_pan', models.CharField(blank=True, max_length=32, null=True)),
                ('to_gst', models.CharField(blank=True, max_length=32, null=True)),
                ('to_addr_line_1', models.TextField(blank=True, null=True)),
                ('to_addr_line_2', models.TextField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('roundoff', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('boe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_trades', to='bill_of_entry.billofentrymodel')),
                ('from_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_from_company', to='core.companymodel')),
                ('to_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_to_company', to='core.companymodel')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='LicenseTradeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('mode', models.CharField(choices=[('QTY', 'Quantity (Kg × Rate)'), ('CIF_INR', 'CIF (INR × %)'), ('FOB_INR', 'FOB (INR × %)')], db_index=True, default='QTY', max_length=10)),
                ('qty_kg', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('rate_inr_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('cif_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('fob_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('pct', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=9)),
                ('amount_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('sr_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_lines', to='license.licenseimportitemsmodel')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='license.licensetrade')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
