# Generated by Django 4.2.21 on 2025-09-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0040_licensetrade_licensetradeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensetradeline',
            name='sr_number',
        ),
        migrations.RemoveField(
            model_name='licensetradeline',
            name='trade',
        ),
        migrations.DeleteModel(
            name='LicenseTrade',
        ),
        migrations.DeleteModel(
            name='LicenseTradeLine',
        ),
    ]
