# Generated by Django 4.2.21 on 2025-10-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0041_remove_licensetradeline_sr_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='modified_on',
        ),
    ]
